### ISSUE TITLE
Project is bad influence on the children

### ISSUE THREAD

**Issue by jmhertlein** [LinuxMercedes/hashpipe#2]
As a parent, I object strongly to the suggestive nature of this project and its title. I am concerned that seeing such language, even when used as a joke, may lead our children down a destructive path rife with addiction, anti-social behavior, dangerous anti-establishment thinking, and drastically unnatural moral leanings.

I am also worried that it may encourage youths to try marijuana, though compared to what using UNIX can do to you, I am only peripherally concerned.

Also, the fact that there is an option to disable SSL is just perverted. I can't believe GitHub is willing to host something like this.

Finally, I think you may want to check your firewall logs, I think someone replaced your standard GPLv3 LICENSE file with the one from that school in the northeast where they can't keep the students off the roof.

**Comment by LinuxMercedes** [comment]
![marihuana](http://31.media.tumblr.com/tumblr_ln99tagKma1qlztoqo1_500.jpg)

I suppose, given the title of the project, I ought to have used the license from the pot-smoking hippies in the southwest instead.

[Also, in case this wasn't stuck in your head already, it is now.](https://www.youtube.com/watch?v=_9BGLtqqkVI)
